import type { Trade, DashboardStats } from "./types"

export const mockTrades: Trade[] = [
  {
    id: "1",
    symbol: "NIFTY 50",
    date: "2025-06-22",
    entryPrice: 100,
    exitPrice: 120,
    quantity: 150,
    direction: "long",
    stopLoss: 10,
    target: 20,
    strategy: "Breakout",
    outcome: "full-success",
    pnl: 3000,
    pnlPercent: 20,
    riskReward: "1:0.22",
    tradeAnalysis: "Clean breakout above resistance with volume confirmation.",
    entryConfidence: 8,
    satisfaction: 9,
    emotionalState: "calm",
    mistakes: [],
    lessonsLearned: "Patience pays off when waiting for proper setup.",
  },
  {
    id: "2",
    symbol: "NIFTY 50",
    date: "2025-06-18",
    entryPrice: 35.2,
    exitPrice: 55.4,
    quantity: 75,
    direction: "long",
    stopLoss: 5,
    target: 25,
    strategy: "Breakout",
    outcome: "full-success",
    pnl: 1515,
    pnlPercent: 57.39,
    riskReward: "1:3.88",
    tradeAnalysis: "Strong momentum continuation trade.",
    entryConfidence: 7,
    satisfaction: 8,
    emotionalState: "calm",
    mistakes: [],
    lessonsLearned: "Following the trend works well in momentum markets.",
  },
  {
    id: "3",
    symbol: "SENSEX",
    date: "2025-06-13",
    entryPrice: 404,
    exitPrice: 328,
    quantity: 20,
    direction: "long",
    stopLoss: 30,
    target: 80,
    strategy: "Breakout",
    outcome: "followed-plan",
    pnl: -1520,
    pnlPercent: -18.81,
    riskReward: "1:1.41",
    tradeAnalysis: "Followed plan but market reversed unexpectedly.",
    entryConfidence: 6,
    satisfaction: 5,
    emotionalState: "calm",
    mistakes: [],
    lessonsLearned: "Sometimes even good setups fail. Stick to the plan.",
  },
  {
    id: "4",
    symbol: "NIFTY 50",
    date: "2025-06-12",
    entryPrice: 50.05,
    exitPrice: 79.55,
    quantity: 75,
    direction: "long",
    stopLoss: 8,
    target: 35,
    strategy: "Reversal",
    outcome: "full-success",
    pnl: 2212.5,
    pnlPercent: 58.94,
    riskReward: "1:2.94",
    tradeAnalysis: "Perfect reversal at support level.",
    entryConfidence: 8,
    satisfaction: 9,
    emotionalState: "calm",
    mistakes: [],
    lessonsLearned: "Support levels provide excellent R:R opportunities.",
  },
  {
    id: "5",
    symbol: "SENSEX",
    date: "2025-06-10",
    entryPrice: 167.65,
    exitPrice: 91,
    quantity: 20,
    direction: "long",
    stopLoss: 15,
    target: 50,
    strategy: "Pullback",
    outcome: "mistake",
    pnl: -1533,
    pnlPercent: -45.72,
    riskReward: "1:1",
    tradeAnalysis: "Ignored stop loss, held hoping for recovery.",
    entryConfidence: 4,
    satisfaction: 2,
    emotionalState: "overconfident",
    mistakes: ["Ignored Stop Loss"],
    lessonsLearned: "Never move stop loss. Accept the loss and move on.",
  },
  {
    id: "6",
    symbol: "NIFTY 50",
    date: "2025-06-05",
    entryPrice: 28.3,
    exitPrice: 39.5,
    quantity: 150,
    direction: "long",
    stopLoss: 5,
    target: 15,
    strategy: "Reversal",
    outcome: "full-success",
    pnl: 5040,
    pnlPercent: 39.58,
    riskReward: "1:2.11",
    tradeAnalysis: "Caught the bottom reversal perfectly.",
    entryConfidence: 7,
    satisfaction: 9,
    emotionalState: "calm",
    mistakes: [],
    lessonsLearned: "Oversold conditions with volume spike = good entry.",
  },
]

export const mockDashboardStats: DashboardStats = {
  highestPnl: 37299,
  winRate: 75,
  avgRiskReward: "1:3.43",
  tradesThisMonth: 8,
  confidenceIndex: 85,
}

export const mockCumulativePnl = [
  { date: "Jun 1", pnl: 0 },
  { date: "Jun 5", pnl: 5040 },
  { date: "Jun 10", pnl: 3507 },
  { date: "Jun 12", pnl: 5720 },
  { date: "Jun 13", pnl: 4200 },
  { date: "Jun 18", pnl: 5715 },
  { date: "Jun 22", pnl: 8715 },
]

export const mockTopTrades = [
  { symbol: "SENSEX", pnl: 37299, pnlPercent: 129.31 },
  { symbol: "NIFTY 50", pnl: 5040, pnlPercent: 39.58 },
  { symbol: "NIFTY 50", pnl: 3000, pnlPercent: 20.0 },
]

export const strategies = ["Breakout", "Reversal", "Pullback", "Trend", "News-based"]
export const emotionalStates = ["Calm", "Overconfident", "Impatient", "Frustrated", "Anxious"]
export const outcomes = ["Full Success", "Partial", "Breakeven", "Followed Plan", "Mistake"]
export const mistakeOptions = [
  "Overtrading",
  "Revenge Trading",
  "Risked Too Much",
  "Exited Too Early",
  "Exited Too Late",
  "FOMO Entry",
  "Ignored Signals",
  "No Clear Plan",
  "Ignored Stop Loss",
  "No Mistakes",
]
